package webapp.web.group;


public interface GroupsSQL {

	String READ_QUESTIONS = " SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user " 
                + " ON q.post_by = user.student_id"
                + " WHERE g.university_id IS NULL ";
	
	String READ_QUESTION_BY_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " WHERE g.university_id IS NULL "
                + " AND description=? ;";

	String READ_QUESTIONS_BY_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " WHERE g.university_id IS NULL "
                + " AND tags=? ;";

	String READ_QUESTION_BY_DESCRIPTION_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " WHERE g.university_id IS NULL "
                + " AND description=? AND tags=? ;";
        
        
        String READ_QUESTIONS_BY_DEGREE_NAME = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id INNER JOIN "
                + " student_login user "
                + " ON q.post_by = user.student_id "
                + " INNER JOIN degree d "
                + " ON g.degree_id=d.degree_id "
                + " WHERE g.university_id IS NULL "
                + " AND g.program_id IS NULL "
                + " AND d.degree_name=? ;";
        
        String READ_QUESTIONS_BY_DEGREE_NAME_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " INNER JOIN degree d "
                + "  ON g.degree_id=d.degree_id "
                + " WHERE g.university_id IS NULL "
                + " AND g.program_id IS NULL "
                + " AND d.degree_name=? "
                + " AND q.description=? ;";
        
        String READ_QUESTIONS_BY_DEGREE_NAME_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " INNER JOIN degree d "
                + " ON g.degree_id=d.degree_id "
                + " WHERE g.university_id IS NULL "
                + " AND g.program_id IS NULL "
                + " AND d.degree_name=? "
                + " AND q.tags=? ;";
        
        String READ_QUESTIONS_BY_DEGREE_NAME_AND_TAGS_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user"
                + " ON q.post_by = user.student_id "
                + " INNER JOIN degree d ON "
                + " g.degree_id=d.degree_id "
                + " WHERE g.university_id IS NULL "
                + " AND g.program_id IS NULL "
                + " AND d.degree_name=? "
                + " AND q.tags=? "
                + " AND q.description=?  ;";
        
        String READ_QUESTIONS_BY_PROGRAM_NAME = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " INNER JOIN program p "
                + " ON g.program_id=p.program_id "
                + " WHERE g.university_id IS NULL "
                + " AND g.degree_id IS NULL "
                + " AND p.program_name=? ;";
        
        String READ_QUESTIONS_BY_PROGRAM_NAME_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " INNER JOIN program p "
                + " ON g.program_id=p.program_id "
                + " WHERE g.university_id IS NULL "
                + " AND g.degree_id IS NULL "
                + " AND p.program_name=? "
                + " AND q.tags=? ;";
        
        String READ_QUESTIONS_BY_PROGRAM_NAME_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                + " FROM questions_details q "
                + " INNER JOIN groups g "
                + " ON q.group_id=g.group_id "
                + " INNER JOIN student_login user "
                + " ON q.post_by = user.student_id "
                + " INNER JOIN program p "
                + " ON g.program_id=p.program_id "
                + " WHERE g.university_id IS NULL "
                + " AND g.degree_id IS NULL "
                + " AND p.program_name=? "
                + " AND q.description=? ;";
        
         String READ_QUESTIONS_BY_PROGRAM_NAME_AND_TAGS_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                 + " FROM questions_details q "
                 + " INNER JOIN groups g "
                 + " ON q.group_id=g.group_id "
                 + " INNER JOIN student_login user "
                 + " ON q.post_by = user.student_id "
                 + " INNER JOIN program p "
                 + " ON g.program_id=p.program_id "
                 + " WHERE g.university_id IS NULL "
                 + " AND g.degree_id IS NULL "
                 + " AND p.program_name=? "
                 + " AND q.tags=? "
                 + " AND q.description=? ;";
         
         String READ_QUESTIONS_BY_DEGREE_NAME_AND_PROGRAM_NAME = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                 + " FROM questions_details q "
                 + " INNER JOIN groups g "
                 + " ON q.group_id=g.group_id "
                 + " INNER JOIN student_login user "
                 + " ON q.post_by = user.student_id "
                 + " INNER JOIN program p "
                 + " ON g.program_id=p.program_id "
                 + " INNER JOIN degree d "
                 + " ON g.degree_id=d.degree_id"
                 + " WHERE g.university_id IS NULL "
                 + " AND d.degree_name=? "
                 + " AND p.program_name=?;";
         
         String READ_QUESTIONS_BY_DEGREE_NAME_AND_PROGRAM_NAME_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                 + " FROM questions_details q "
                 + " INNER JOIN groups g "
                 + " ON q.group_id=g.group_id "
                 + " INNER JOIN student_login user "
                 + " ON q.post_by = user.student_id "
                 + " INNER JOIN program p "
                 + " ON g.program_id=p.program_id "
                 + " INNER JOIN degree d "
                 + " ON g.degree_id=d.degree_id "
                 + " WHERE g.university_id IS NULL "
                 + " AND d.degree_name=? "
                 + " AND p.program_name=? "
                 + " AND q.tags=? ;";
         
         String READ_QUESTIONS_BY_DEGREE_NAME_AND_PROGRAM_NAME_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                 + " FROM questions_details q "
                 + " INNER JOIN groups g "
                 + " ON q.group_id=g.group_id "
                 + " INNER JOIN student_login user "
                 + " ON q.post_by = user.student_id "
                 + " INNER JOIN program p "
                 + " ON g.program_id=p.program_id "
                 + " INNER JOIN degree d "
                 + " ON g.degree_id=d.degree_id "
                 + " WHERE g.university_id IS NULL "
                 + " AND d.degree_name=? "
                 + " AND p.program_name=? "
                 + " AND q.description=? ;";
         
         String READ_QUESTIONS_BY_DEGREE_NAME_AND_PROGRAM_NAME_AND_TAGS_AND_DESCRIPTIONS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
                 + " FROM questions_details q "
                 + " INNER JOIN groups g "
                 + " ON q.group_id=g.group_id "
                 + " INNER JOIN student_login user "
                 + " ON q.post_by = user.student_id "
                 + " INNER JOIN program p "
                 + " ON g.program_id=p.program_id "
                 + " INNER JOIN degree d "
                 + " ON g.degree_id=d.degree_id "
                 + " WHERE g.university_id IS NULL "
                 + " AND d.degree_name=? "
                 + " AND p.program_name=? "
                 + " AND q.tags=? "
                 + " AND q.description=? ;";
         
          String READ_QUESTIONS_BY_UNIVERSITY_NAME = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
            + " FROM questions_details q "
            + " INNER JOIN groups g "
            + " ON g.group_id=q.group_id "
            + " INNER JOIN university u "
            + " ON g.university_id=u.university_id "
            + " INNER JOIN student_login user "
            + " ON q.post_by = user.student_id "
            + " AND u.university_name=? ;";
    
    String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
            + " FROM questions_details q "
            + " INNER JOIN groups g "
            + " ON g.group_id=q.group_id "
            + " INNER JOIN university u "
            + " ON g.university_id=u.university_id "
            + " INNER JOIN student_login user "
            + " ON q.post_by = user.student_id "
            + " AND u.university_name=? "
            + " AND q.description=? ;";
    
    String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DESCRIPTION_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
            + " FROM questions_details q "
            + " INNER JOIN groups g "
            + " ON g.group_id=q.group_id "
            + " INNER JOIN university u "
            + " ON g.university_id=u.university_id "
            + " INNER JOIN student_login user "
            + " ON q.post_by = user.student_id "
            + " AND u.university_name=? "
            + " AND q.description=? "
            + " AND q.tags= ? ; ";
    
    
    String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
            + " FROM questions_details q "
            + " INNER JOIN groups g "
            + " ON g.group_id=q.group_id "
            + " INNER JOIN university u "
            + " ON g.university_id=u.university_id "
            + " INNER JOIN student_login user "
            + " ON q.post_by = user.student_id "
            + " AND u.university_name=? "
            + " AND q.tags=? ; "; 
    
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN degree d "
               + " ON g.degree_id=d.degree_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND d.degree_name=? ;;";
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + "FROM questions_details q "
               + "INNER JOIN groups g "
               + "ON g.group_id=q.group_id "
               + "INNER JOIN university u "
               + "ON g.university_id=u.university_id "
               + "INNER JOIN degree d "
               + "ON g.degree_id=d.degree_id "
               + "INNER JOIN student_login user "
               + "ON q.post_by = user.student_id "
               + "AND u.university_name=? "
               + "AND d.degree_name=? "
               + "AND q.description=?;";
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN degree d "
               + " ON g.degree_id=d.degree_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND d.degree_name=? "
               + " AND q.tags=? ;";
       
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME_AND_TAGS_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN degree d "
               + " ON g.degree_id=d.degree_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND d.degree_name=? "
               + " AND q.tags=? "
               + " AND q.description=?;";
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_PROGRAM_NAME = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN program p "
               + " ON g.program_id=p.program_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND p.program_name=? ;";
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_PROGRAM_NAME_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN program p "
               + " ON g.program_id=p.program_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND p.program_name=? "
               + " AND q.tags=? ;";
       
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_PROGRAM_NAME_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN program p "
               + " ON g.program_id=p.program_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND p.program_name=? "
               + " AND q.description=?  ;";
       
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_PROGRAM_NAME_AND_TAGS_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN program p "
               + " ON g.program_id=p.program_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND p.program_name=? "
               + " AND q.tags=? "
               + " AND q.description=? ; ;";
       
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME_AND_PROGRAM_NAME = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + "FROM questions_details q "
               + "INNER JOIN groups g "
               + "ON g.group_id=q.group_id "
               + "INNER JOIN university u "
               + "ON g.university_id=u.university_id "
               + "INNER JOIN program p "
               + "ON g.program_id=p.program_id "
               + "INNER JOIN degree d "
               + "ON g.degree_id=d.degree_id "
               + "INNER JOIN student_login user "
               + "ON q.post_by = user.student_id "
               + "AND u.university_name=? "
               + "AND d.degree_name=? "
               + "AND p.program_name=? ;";
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME_AND_PROGRAM_NAME_AND_TAGS = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN program p "
               + " ON g.program_id=p.program_id "
               + " INNER JOIN degree d "
               + " ON g.degree_id=d.degree_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND d.degree_name=? "
               + " AND p.program_name=? "
               + " AND q.tags=?;";
       
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME_AND_PROGRAM_NAME_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + " FROM questions_details q "
               + " INNER JOIN groups g "
               + " ON g.group_id=q.group_id "
               + " INNER JOIN university u "
               + " ON g.university_id=u.university_id "
               + " INNER JOIN program p "
               + " ON g.program_id=p.program_id "
               + " INNER JOIN degree d "
               + " ON g.degree_id=d.degree_id "
               + " INNER JOIN student_login user "
               + " ON q.post_by = user.student_id "
               + " AND u.university_name=? "
               + " AND d.degree_name=? "
               + " AND p.program_name=? "
               + " AND q.description=? ;";
       
       String READ_QUESTIONS_BY_UNIVERSITY_NAME_AND_DEGREE_NAME_AND_PROGRAM_NAME_AND_TAGS_AND_DESCRIPTION = "SELECT q.question_id,q.group_id,q.post_by,q.tags,q.description,q.post_on, CONCAT(user.first_name,' ', user.last_name) "
               + "FROM questions_details q "
               + "INNER JOIN groups g "
               + "ON g.group_id=q.group_id "
               + "INNER JOIN university u "
               + "ON g.university_id=u.university_id "
               + "INNER JOIN program p "
               + "ON g.program_id=p.program_id "
               + "INNER JOIN degree d "
               + "ON g.degree_id=d.degree_id "
               + "INNER JOIN student_login user "
               + "ON q.post_by = user.student_id "
               + "AND u.university_name=? "
               + "AND d.degree_name=? "
               + "AND p.program_name=? "
               + "AND q.tags=?"
               + "AND q.description=? ;";
               
                 
}
